LootJS.modifiers((event) => {
    // Matches any loot table that contains "chests" in its path (vanilla and modded dungeons)
    event.addLootTableModifier(/.*:chests\/.*/)
        .replaceLoot('tfc:metal/double_ingot/wrought_iron', 'tfc:metal/double_ingot/cast_iron', true)
        .replaceLoot('minecraft:iron_ingot', 'tfc:metal/ingot/cast_iron', true)
        .replaceLoot('minecraft:gold_ingot', 'tfc:metal/ingot/gold', true)
        .replaceLoot('minecraft:copper_ingot', 'tfc:metal/ingot/copper', true)
        .replaceLoot('minecraft:bucket', 'tfc:wooden_bucket', true)
        .replaceLoot('minecraft:stone_pickaxe', 'tfc:metal/pickaxe/copper', true)
        .replaceLoot('minecraft:iron_pickaxe', 'tfc:metal/pickaxe/wrought_iron', true)
        .replaceLoot('minecraft:golden_pickaxe', 'tfc:metal/pickaxe/bronze', true)
        .replaceLoot('minecraft:gold_nugget', 'tfc:ore/small_native_gold', true)
        .replaceLoot('minecraft:diamond_pickaxe', 'tfc:metal/pickaxe/steel', true)
        .replaceLoot('minecraft:chainmail_helmet', 'tfc:metal/helmet/copper', true)
        .replaceLoot('minecraft:chainmail_chestplate', 'tfc:metal/chestplate/copper', true)
        .replaceLoot('minecraft:chainmail_leggings', 'tfc:metal/greaves/copper', true)
        .replaceLoot('minecraft:chainmail_boots', 'tfc:metal/boots/copper', true)
        .replaceLoot('minecraft:golden_helmet', 'tfc:metal/helmet/bronze', true)
        .replaceLoot('minecraft:golden_chestplate', 'tfc:metal/chestplate/bronze', true)
        .replaceLoot('minecraft:golden_leggings', 'tfc:metal/greaves/bronze', true)
        .replaceLoot('minecraft:golden_boots', 'tfc:metal/boots/bronze', true)
        .replaceLoot('minecraft:iron_helmet', 'tfc:metal/helmet/wrought_iron', true)
        .replaceLoot('minecraft:iron_chestplate', 'tfc:metal/chestplate/wrought_iron', true)
        .replaceLoot('minecraft:iron_leggings', 'tfc:metal/greaves/wrought_iron', true)
        .replaceLoot('minecraft:iron_boots', 'tfc:metal/boots/wrought_iron', true)
        .replaceLoot('minecraft:diamond_helmet', 'tfc:metal/helmet/steel', true)
        .replaceLoot('minecraft:diamond_chestplate', 'tfc:metal/chestplate/steel', true)
        .replaceLoot('minecraft:diamond_leggings', 'tfc:metal/greaves/steel', true)
        .replaceLoot('minecraft:diamond_boots', 'tfc:metal/boots/steel', true)
        .replaceLoot('minecraft:stone_sword', 'tfc:metal/sword/copper', true)
        .replaceLoot('minecraft:iron_sword', 'tfc:metal/sword/wrought_iron', true)
        .replaceLoot('minecraft:diamond_sword', 'tfc:metal/sword/steel', true)
        .replaceLoot('minecraft:netherite_sword', 'tfc:metal/sword/black_steel', true)
        .replaceLoot('minecraft:netherite_helmet', 'tfc:metal/helmet/black_steel', true)
        .replaceLoot('minecraft:netherite_boots', 'tfc:metal/boots/black_steel', true)
        .replaceLoot('minecraft:carrot', 'tfc:food/carrot', true)
        .replaceLoot('minecraft:potato', 'tfc:food/potato', true)
        .replaceLoot('minecraft:beetroot', 'tfc:food/beet', true)
        .replaceLoot('minecraft:cooked_beef', 'tfc:food/cooked_beef', true)
        .replaceLoot('minecraft:cooked_porkchop', 'tfc:food/cooked_pork', true)
        .replaceLoot('minecraft:cooked_mutton', 'tfc:food/cooked_mutton', true)
        .replaceLoot('minecraft:cooked_chicken', 'tfc:food/cooked_chicken', true)
        .replaceLoot('minecraft:cooked_rabbit', 'tfc:food/cooked_rabbit', true)
        .replaceLoot('minecraft:cooked_cod', 'tfc:food/cooked_mutton', true)
        .replaceLoot('minecraft:cooked_salmon', 'tfc:food/cooked_mutton', true)
        .replaceLoot('minecraft:cooked_mutton', 'tfc:food/cooked_mutton', true)
        .replaceLoot('minecraft:bread', 'tfc:food/wheat_bread', true)
        .replaceLoot('minecraft:iron_shovel', 'tfc:metal/shovel/wrought_iron', true)
        .replaceLoot('railcraft:coal_coke', 'kubejs:coal_coke', true)
        .replaceLoot('immersiveengineering:coal_coke', 'kubejs:coal_coke', true)

    // Matches any loot table that contains "archaeology" in its path (vanilla and modded)
    event.addLootTableModifier(/.*:archaeology\/.*/)
        .replaceLoot('minecraft:wooden_hoe', 'tfc:metal/hoe/copper', true)
        .replaceLoot('minecraft:iron_axe', 'tfc:metal/axe/wrought_iron', true)
        .replaceLoot('minecraft:gold_nugget', 'tfc:ore/small_native_gold', true)
        .replaceLoot('minecraft:wheat', 'tfc:food/wheat', true)
        .replaceLoot('minecraft:wheat_seeds', 'tfc:seeds/wheat', true)
        .replaceLoot('minecraft:beetroot_seeds', 'tfc:seeds/beet', true)

    // Matches any loot table that contains "entities" in its path (vanilla and modded)
    event.addLootTableModifier(/.*:entities\/.*/)
        .replaceLoot('minecraft:iron_ingot', 'tfc:metal/ingot/cast_iron', true)
        .replaceLoot('minecraft:carrot', 'tfc:food/carrot', true)
        .replaceLoot('minecraft:potato', 'tfc:food/potato', true)
        .replaceLoot('minecraft:iron_shovel', 'tfc:metal/shovel/wrought_iron', true)

    // Matches cat gift pool :D
    event.addLootTableModifier("minecraft:gameplay/cat_morning_gift")
        .replaceLoot("minecraft:chicken", "tfc:food/chichen")
});