// Add toolRackCapable to any item
// to allow it to be placed within 
// a Terrafirmacraft Tool Rack!

import net.minecraftforge.oredict.OreDictionary

def items = [
    item('chisel:chisel_iron', OreDictionary.WILDCARD_VALUE),
    item('chisel:chisel_diamond', OreDictionary.WILDCARD_VALUE),
    item('chisel:chisel_hitech', OreDictionary.WILDCARD_VALUE),
    item('powerchisels:fluxed_chisel'),
    item('chiselsandbits:chisel_stone'),
    item('chiselsandbits:chisel_iron'),
    item('chiselsandbits:chisel_gold'),
    item('chiselsandbits:chisel_diamond'),
    item('chiselsandbits:wrench_wood'),
    item('chiselsandbits:bitsaw_diamond'),
    item('chiselsandbits:tape_measure'),
    item('thermalcultivation:watering_can'),
    item('thermalcultivation:watering_can', 1),
    item('thermalcultivation:watering_can', 2),
    item('thermalcultivation:watering_can', 3),
    item('thermalcultivation:watering_can', 4),
    item('thermalcultivation:watering_can', 32000),
    item('thermalexpansion:capacitor'),
    item('thermalexpansion:capacitor', 1),
    item('thermalexpansion:capacitor', 2),
    item('thermalexpansion:capacitor', 3),
    item('thermalexpansion:capacitor', 4),
    item('thermalexpansion:capacitor', 32000),
    item('thermalexpansion:reservoir'),
    item('thermalexpansion:reservoir', 1),
    item('thermalexpansion:reservoir', 2),
    item('thermalexpansion:reservoir', 3),
    item('thermalexpansion:reservoir', 4),
    item('thermalexpansion:reservoir', 32000),
    item('thermalfoundation:meter'),
    item('thermalfoundation:tome_lexicon'),
    item('thermalfoundation:tome_experience'),
    item('thermalinnovation:magnet'),
    item('thermalinnovation:magnet', 1),
    item('thermalinnovation:magnet', 2),
    item('thermalinnovation:magnet', 3),
    item('thermalinnovation:magnet', 4),
    item('thermalinnovation:magnet', 32000),
    item('thermalinnovation:injector'),
    item('thermalinnovation:injector', 1),
    item('thermalinnovation:injector', 2),
    item('thermalinnovation:injector', 3),
    item('thermalinnovation:injector', 4),
    item('thermalinnovation:injector', 32000),
    item('thermalinnovation:quiver'),
    item('thermalinnovation:quiver', 1),
    item('thermalinnovation:quiver', 2),
    item('thermalinnovation:quiver', 3),
    item('thermalinnovation:quiver', 4),
    item('thermalinnovation:quiver', 32000),
    item('immersiveengineering:tool', 2),
    item('immersiveengineering:drill'),
    item('immersiveengineering:jerrycan'),
    item('immersiveengineering:revolver'),
    item('immersiveengineering:chemthrower'),
    item('immersiveengineering:railgun'),
    item('immersiveengineering:skyhook'),
    item('immersivepetroleum:oil_can'),
    item('tfc:spindle'),
    item('storagedrawers:drawer_key'),
    item('storagedrawers:shroud_key'),
    item('storagedrawers:personal_key'),
    item('storagedrawers:quantify_key'),
    item('storagedrawers:tape'),
    item('logisticspipes:pipe_controller'),
    item('logisticspipes:pipe_manager'),
    item('logisticspipes:logistics_programmer'),
    item('logisticspipes:remote_orderer'),
    item('buildcraftsilicon:gate_copier'),
    item('buildinggadgets:buildingtool'),
    item('buildinggadgets:exchangertool'),
    item('buildinggadgets:copypastetool'),
    item('buildinggadgets:destructiontool'),
    item('buildcraftcore:wrench'),
    item('buildcraftcore:paintbrush'),
    item('buildcraftcore:paintbrush', 1),
    item('buildcraftcore:paintbrush', 2),
    item('buildcraftcore:paintbrush', 3),
    item('buildcraftcore:paintbrush', 4),
    item('buildcraftcore:paintbrush', 5),
    item('buildcraftcore:paintbrush', 6),
    item('buildcraftcore:paintbrush', 7),
    item('buildcraftcore:paintbrush', 8),
    item('buildcraftcore:paintbrush', 9),
    item('buildcraftcore:paintbrush', 10),
    item('buildcraftcore:paintbrush', 11),
    item('buildcraftcore:paintbrush', 12),
    item('buildcraftcore:paintbrush', 13),
    item('buildcraftcore:paintbrush', 14),
    item('buildcraftcore:paintbrush', 15),
    item('buildcraftcore:paintbrush', 16),
    item('buildcraftcore:marker_connector'),
    item('appliedenergistics2:certus_quartz_cutting_knife'),
    item('appliedenergistics2:nether_quartz_cutting_knife'),
    item('appliedenergistics2:entropy_manipulator'),
    item('appliedenergistics2:charged_staff'),
    item('appliedenergistics2:matter_cannon'),
    item('appliedenergistics2:portable_cell'),
    item('appliedenergistics2:color_applicator'),
    item('appliedenergistics2:biometric_card'),
    item('appliedenergistics2:memory_card'),
]

def blowpipe = ore_dict.getItems('blowpipe')

for (item in blowpipe) {
    ore_dict.add("toolRackCapable", item)
}

for (item in items) {
    ore_dict.add("toolRackCapable", item)
}
