
[animals]
	#Ticks required after shearing before a sheep can regrow its wool.
	#20 ticks = 1 second. Default: 6000 ticks = 5 minutes.
	#Set to 0 to disable delay (vanilla behavior).
	#Range: > 0
	sheepWoolRegrowthDelayTicks = 6000
	#Ticks required after milking a cow before it can be milked again.
	#20 ticks = 1 second. Default: 1200 ticks = 1 minute.
	#Set to 0 to disable (vanilla behavior).
	#Range: > 0
	cowMilkingDelayTicks = 1200

	[animals.climate]
		#Lerp value to align biome temperatures more closely to their JSON temperature value: [0 - 1]
		#0 to disable and only return the temperature noise value.
		#Default: 0.4
		#Range: 0.0 ~ 1.0
		tempLerpValue = 0.4
		#Whether or not to use the Lerp function to adjust climate temperature towards biome temperature value.
		#Default: true
		doTempLerp = true
		#Value to scale temperature noise to climate temperature value
		#Default: 27.5
		#Range: 4.9E-324 ~ 1.7976931348623157E308
		tempScale = 27.5
		#Value to shift temperature scale.
		#Default: 7.5
		#Range: 4.9E-324 ~ 1.7976931348623157E308
		tempShift = 7.5
		#Value to scale vegetation noise to climate rain value
		#Default: 250
		#Range: 4.9E-324 ~ 1.7976931348623157E308
		rainScale = 250.0

